name: call test git sync workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-git-sync-workflow:
      uses: danaltest2/test-git-sync-workflow/.github/workflows/main.yml@main
