name: call test reusable workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: danaltest2/test-reusable-workflow/.github/workflows/main.yml@main
